In [1]:
import polars as pl

In [ ]:
lf = pl.scan_csv('./dataset/train.csv', separator=';')
display(lf.head(10).collect())

shape: (10, 14)
┌─────────┬───────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tran_no ┆ device_no ┆ tran_date_ ┆ begin_dat ┆ … ┆ pass_rout ┆ ngpt_rout ┆ bus_exit_ ┆ garage_nu │
│ ---     ┆ ---       ┆ time       ┆ e_time    ┆   ┆ e         ┆ e         ┆ no        ┆ mber      │
│ i64     ┆ i64       ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆           ┆ str        ┆ str       ┆   ┆ str       ┆ str       ┆ i64       ┆ i64       │
╞═════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 23480   ┆ 1734655   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 205       ┆ 31117     │
│         ┆           ┆ 18:17:55   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 18:18:00  ┆   ┆           ┆           ┆           ┆           │
│ 23481   ┆ 1734655   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 205       ┆ 31117     │
│         ┆           ┆ 18:17:58   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 18:18:00  ┆   ┆           ┆           ┆           ┆           │
│ 27701   ┆ 1736716   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 201       ┆ 31046     │
│         ┆           ┆ 06:03:04   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:04:00  ┆   ┆           ┆           ┆           ┆           │
│ 25208   ┆ 1736314   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ null      ┆ 25        ┆ 201       ┆ 31046     │
│         ┆           ┆ 06:24:42   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:24:00  ┆   ┆           ┆           ┆           ┆           │
│ 13657   ┆ 1736745   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ null      ┆ 25        ┆ 204       ┆ 31121     │
│         ┆           ┆ 06:25:43   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:25:00  ┆   ┆           ┆           ┆           ┆           │
│ 19125   ┆ 1736098   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 06:33:05   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:34:00  ┆   ┆           ┆           ┆           ┆           │
│ 24469   ┆ 1849494   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 203       ┆ 31106     │
│         ┆           ┆ 06:39:40   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:40:00  ┆   ┆           ┆           ┆           ┆           │
│ 27702   ┆ 1736716   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 201       ┆ 31046     │
│         ┆           ┆ 06:41:09   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:41:00  ┆   ┆           ┆           ┆           ┆           │
│ 31155   ┆ 1734566   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 201       ┆ 31046     │
│         ┆           ┆ 06:46:33   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:46:00  ┆   ┆           ┆           ┆           ┆           │
│ 23288   ┆ 1736610   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 201       ┆ 31046     │
│         ┆           ┆ 06:46:52   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:46:00  ┆   ┆           ┆           ┆           ┆           │
└─────────┴───────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
df = lf.filter(
    # pl.col('garage_number') == 31075,
    pl.col('ngpt_route') == '25 трамвай'
).with_columns(
    pl.col('tran_date_time').str.to_datetime(format="%Y-%m-%d %H:%M:%S")
).filter(
    pl.col('tran_date_time') >= pl.datetime(2025, 1, 1),
    pl.col('tran_date_time') < pl.datetime(2025, 1, 2)
).collect()

display(df)

shape: (377, 14)
┌─────────┬───────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tran_no ┆ device_no ┆ tran_date_ ┆ begin_dat ┆ … ┆ pass_rout ┆ ngpt_rout ┆ bus_exit_ ┆ garage_nu │
│ ---     ┆ ---       ┆ time       ┆ e_time    ┆   ┆ e         ┆ e         ┆ no        ┆ mber      │
│ i64     ┆ i64       ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆           ┆ datetime[μ ┆ str       ┆   ┆ str       ┆ str       ┆ i64       ┆ i64       │
│         ┆           ┆ s]         ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 19125   ┆ 1736098   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 06:33:05   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:34:00  ┆   ┆           ┆           ┆           ┆           │
│ 28221   ┆ 1736672   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 06:48:56   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:48:00  ┆   ┆           ┆           ┆           ┆           │
│ 23078   ┆ 1736093   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 06:55:29   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:55:00  ┆   ┆           ┆           ┆           ┆           │
│ 22403   ┆ 1734659   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ null      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 07:22:32   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 07:22:00  ┆   ┆           ┆           ┆           ┆           │
│ 22404   ┆ 1734659   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 07:46:41   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 07:46:00  ┆   ┆           ┆           ┆           ┆           │
│ …       ┆ …         ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 23157   ┆ 1736093   ┆ 2025-01-01 ┆ null      ┆ … ┆ null      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 20:44:23   ┆           ┆   ┆           ┆ трамвай   ┆           ┆           │
│ 27840   ┆ 1736308   ┆ 2025-01-01 ┆ null      ┆ … ┆ null      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 20:44:22   ┆           ┆   ┆           ┆ трамвай   ┆           ┆           │
│ 28310   ┆ 1736672   ┆ 2025-01-01 ┆ null      ┆ … ┆ null      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 21:49:28   ┆           ┆   ┆           ┆ трамвай   ┆           ┆           │
│ 28311   ┆ 1736672   ┆ 2025-01-01 ┆ null      ┆ … ┆ null      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 21:49:37   ┆           ┆   ┆           ┆ трамвай   ┆           ┆           │
│ 28312   ┆ 1736672   ┆ 2025-01-01 ┆ null      ┆ … ┆ null      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 21:50:44   ┆           ┆   ┆           ┆ трамвай   ┆           ┆           │
└─────────┴───────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [17]:
df.sort('tran_date_time')

shape: (377, 14)
┌─────────┬───────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tran_no ┆ device_no ┆ tran_date_ ┆ begin_dat ┆ … ┆ pass_rout ┆ ngpt_rout ┆ bus_exit_ ┆ garage_nu │
│ ---     ┆ ---       ┆ time       ┆ e_time    ┆   ┆ e         ┆ e         ┆ no        ┆ mber      │
│ i64     ┆ i64       ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆           ┆ datetime[μ ┆ str       ┆   ┆ str       ┆ str       ┆ i64       ┆ i64       │
│         ┆           ┆ s]         ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 19125   ┆ 1736098   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 06:33:05   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:34:00  ┆   ┆           ┆           ┆           ┆           │
│ 28221   ┆ 1736672   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 06:48:56   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:48:00  ┆   ┆           ┆           ┆           ┆           │
│ 23078   ┆ 1736093   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 06:55:29   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:55:00  ┆   ┆           ┆           ┆           ┆           │
│ 22403   ┆ 1734659   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ null      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 07:22:32   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 07:22:00  ┆   ┆           ┆           ┆           ┆           │
│ 22404   ┆ 1734659   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 07:46:41   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 07:46:00  ┆   ┆           ┆           ┆           ┆           │
│ …       ┆ …         ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 23162   ┆ 1736093   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 21:46:31   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 21:47:00  ┆   ┆           ┆           ┆           ┆           │
│ 22461   ┆ 1734659   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ null      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 21:49:19   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 21:49:00  ┆   ┆           ┆           ┆           ┆           │
│ 28310   ┆ 1736672   ┆ 2025-01-01 ┆ null      ┆ … ┆ null      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 21:49:28   ┆           ┆   ┆           ┆ трамвай   ┆           ┆           │
│ 28311   ┆ 1736672   ┆ 2025-01-01 ┆ null      ┆ … ┆ null      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 21:49:37   ┆           ┆   ┆           ┆ трамвай   ┆           ┆           │
│ 28312   ┆ 1736672   ┆ 2025-01-01 ┆ null      ┆ … ┆ null      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 21:50:44   ┆           ┆   ┆           ┆ трамвай   ┆           ┆           │
└─────────┴───────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [18]:
df.unique(subset=['bus_exit_no'])

shape: (1, 14)
┌─────────┬───────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tran_no ┆ device_no ┆ tran_date_ ┆ begin_dat ┆ … ┆ pass_rout ┆ ngpt_rout ┆ bus_exit_ ┆ garage_nu │
│ ---     ┆ ---       ┆ time       ┆ e_time    ┆   ┆ e         ┆ e         ┆ no        ┆ mber      │
│ i64     ┆ i64       ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆           ┆ datetime[μ ┆ str       ┆   ┆ str       ┆ str       ┆ i64       ┆ i64       │
│         ┆           ┆ s]         ┆           ┆   ┆           ┆           ┆           ┆           │
╞═════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 19125   ┆ 1736098   ┆ 2025-01-01 ┆ 2025-01-0 ┆ … ┆ НГПТ      ┆ 25        ┆ 202       ┆ 31075     │
│         ┆           ┆ 06:33:05   ┆ 1         ┆   ┆           ┆ трамвай   ┆           ┆           │
│         ┆           ┆            ┆ 06:34:00  ┆   ┆           ┆           ┆           ┆           │
└─────────┴───────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘